{{- if .Values.proxy.enabled -}}
{{- $clusterRole := "proxy" -}}
{{- $fullName := include "rocketmq.proxy.fullname" . -}}
{{- $configmapName := include "rocketmq.configmap.fullname" . -}}
{{- $image := printf "%s:%s" .Values.image.repository .Values.image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName | quote }}
  labels:
    {{- include "rocketmq.labels" $ | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "rocketmq.selectorLabels" $ | nindent 6 }}
      component: {{ $clusterRole }}
  template:
    metadata:
      labels:
        {{- include "rocketmq.selectorLabels" $ | nindent 8 }}
        component: {{ $clusterRole }}
    spec:
      {{- with $.Values.proxy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if not $.Values.proxy.affinityOverride }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 5
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  {{- include "rocketmq.selectorLabels" $ | nindent 18 }}
                  component: proxy
              topologyKey: kubernetes.io/hostname
      {{- else if $.Values.proxy.affinityOverride }}
      affinity:
        {{- toYaml $.Values.proxy.affinityOverride | nindent 8 }}
      {{- end }}
      {{- with $.Values.proxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: proxy
        image: {{ $image | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
        command:
          - sh
          #- mqnamesrv
          - /mq-server-start.sh
        env:
        - name: NAMESRV_ADDR
          value: {{ include "rocketmq.nameserver.addr" . }}
        - name: ROCKETMQ_PROCESS_ROLE
          value: {{ $clusterRole }}
        - name: RMQ_PROXY_CONFIG_PATH
          value: /etc/rocketmq/proxy.json
        - name: ROCKETMQ_JAVA_OPTIONS_HEAP
          {{- $maxHeapSize := .Values.proxy.jvm.maxHeapSize }}
          value: {{ printf "-Xms%s -Xmx%s" $maxHeapSize $maxHeapSize }}
        {{- if .Values.proxy.jvm.javaOptsOverride }}
        - name: ROCKETMQ_JAVA_OPTIONS_OVERRIDE
          value: {{ .Values.proxy.jvm.javaOptsOverride }}
        {{- end }}
        ports:
        - name: main
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
        resources:
          {{- toYaml .Values.proxy.resources | nindent 10 }}
        {{- with .Values.proxy.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.proxy.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 5; ./mqshutdown {{ $clusterRole }}"]
        volumeMounts:
        - mountPath: /mq-server-start.sh
          name: mq-server-start-sh
          subPath: mq-server-start.sh
        - mountPath: /etc/rocketmq/proxy.json
          name: proxy-json
          subPath: proxy.json
      dnsPolicy: ClusterFirst
      terminationGracePeriodSeconds: {{ $.Values.proxy.terminationGracePeriodSeconds | default 15 }}
      volumes:
      - configMap:
          items:
          - key: mq-server-start.sh
            path: mq-server-start.sh
          name: {{ $configmapName }}
        name: mq-server-start-sh
      - configMap:
          items:
          - key: proxy.json
            path: proxy.json
          name: {{ $configmapName }}
        name: proxy-json
{{- end }}