apiVersion: v2
name: rocketmq-cluster
description: RocketMQ Helm chart
type: application

version: 11.0.1
appVersion: '5.1.4'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache