apiVersion: v2
name: rocketmq-cluster
description: RocketMQ Helm chart
type: application

version: 11.1.0
appVersion: '5.2.0'

maintainers:
  - name: itboon
    url: 'https://github.com/itboon/rocketmq-helm'

keywords:
  - rocketmq
  - kubernetes
  - apache